version: "2"
services:
  web:
    build: ./front
    ports:
      - 4200:80
  backend:
    build: ./back
    container_name: backend
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017